docs_dir: manuals
extra_css:
- extra.css
markdown_extensions:
- toc:
    permalink: true
nav:
- Programming:
  - C++:
    - C++ Debugging and Profiling: Programming/C++/C++ Debugging and Profiling.md
    - C++ Manual: Programming/C++/C++ Manual.md
    - C++ Workflow: Programming/C++/C++ Workflow.md
    - CMake Manual: Programming/C++/CMake Manual.md
  - Java:
    - Debugging Java: Programming/Java/Debugging Java.md
    - Java Programming Guide: Programming/Java/Java Programming Guide.md
    - Java Workflow: Programming/Java/Java Workflow.md
    - Maven: Programming/Java/Maven.md
  - mosek:
    - xml: []
  - Python:
    - Matplotlib Manual: Programming/Python/Matplotlib Manual.md
    - Pandas Manual: Programming/Python/Pandas Manual.md
    - Plotly Manual: Programming/Python/Plotly Manual.md
    - Python Debugging: Programming/Python/Python Debugging.md
    - Python Manual: Programming/Python/Python Manual.md
    - Python Workflow: Programming/Python/Python Workflow.md
  - Web:
    - CSS Manual: Programming/Web/CSS Manual.md
    - htaccess: Programming/Web/htaccess.md
    - JavaScript: Programming/Web/JavaScript.md
    - Jekyll: Programming/Web/Jekyll.md
  - Common: Programming/Common.md
  - Google API and Apps Script: Programming/Google API and Apps Script.md
  - Gurobi: Programming/Gurobi.md
  - JSON: Programming/JSON.md
  - Overpass Manual: Programming/Overpass Manual.md
  - PostgreSQL Manual: Programming/PostgreSQL Manual.md
  - RCI cluster: Programming/RCI cluster.md
  - Regex: Programming/Regex.md
  - Ruby Workflow: Programming/Ruby Workflow.md
  - Slurm: Programming/Slurm.md
  - SQL Manual: Programming/SQL Manual.md
- LaTeX:
  - package manuals: []
  - Latex manual: LaTeX/Latex manual.md
- Ubuntu:
  - Linux Manual: Ubuntu/Linux Manual.md
- Windows:
  - Powershell Manual: Windows/Powershell Manual.md
  - Windows Manual: Windows/Windows Manual.md
- FFMpeg: FFMpeg.md
- index: index.md
- QGIS: QGIS.md
site_name: Manuals
theme:
  name: mkdocs
  navigation_depth: 8
