docs_dir: manuals
extra_css:
- extra.css
markdown_extensions:
- toc:
    permalink: true
nav:
- Programming:
  - C++:
    - C Manual: Programming/C++/C Manual.md
    - C++ Debugging and Profiling: Programming/C++/C++ Debugging and Profiling.md
    - C++ Manual: Programming/C++/C++ Manual.md
    - C++ Workflow: Programming/C++/C++ Workflow.md
    - CMake Manual: Programming/C++/CMake Manual.md
    - Google Test: Programming/C++/Google Test.md
  - Cloud computing:
    - Lmod: Programming/Cloud computing/Lmod.md
    - RCI cluster: Programming/Cloud computing/RCI cluster.md
    - Slurm: Programming/Cloud computing/Slurm.md
  - Database:
    - Database Workflow: Programming/Database/Database Workflow.md
    - PostgreSQL Debugging and Profiling: Programming/Database/PostgreSQL Debugging
        and Profiling.md
    - PostgreSQL Manual: Programming/Database/PostgreSQL Manual.md
    - SQL Manual: Programming/Database/SQL Manual.md
  - Java:
    - Debugging Java: Programming/Java/Debugging Java.md
    - Jackson: Programming/Java/Jackson.md
    - Java Manual: Programming/Java/Java Manual.md
    - Java Workflow: Programming/Java/Java Workflow.md
    - Maven: Programming/Java/Maven.md
  - Python:
    - Matplotlib Manual: Programming/Python/Matplotlib Manual.md
    - Pandas Manual: Programming/Python/Pandas Manual.md
    - Plotly Manual: Programming/Python/Plotly Manual.md
    - Python Debugging: Programming/Python/Python Debugging.md
    - Python Manual: Programming/Python/Python Manual.md
    - Python Workflow: Programming/Python/Python Workflow.md
  - Web:
    - CSS Manual: Programming/Web/CSS Manual.md
    - css: Programming/Web/css.md
    - Google API and Apps Script: Programming/Web/Google API and Apps Script.md
    - htaccess: Programming/Web/htaccess.md
    - JavaScript: Programming/Web/JavaScript.md
    - Jekyll: Programming/Web/Jekyll.md
    - mkdocs: Programming/Web/mkdocs.md
    - Selenium: Programming/Web/Selenium.md
  - Common: Programming/Common.md
  - Git: Programming/Git.md
  - Gurobi: Programming/Gurobi.md
  - HDF: Programming/HDF.md
  - JSON: Programming/JSON.md
  - Native Libraries: Programming/Native Libraries.md
  - Neural Networks: Programming/Neural Networks.md
  - Perl: Programming/Perl.md
  - Regex: Programming/Regex.md
  - Ruby Workflow: Programming/Ruby Workflow.md
- LaTeX:
  - Latex manual: LaTeX/Latex manual.md
  - LaTeX workflow: LaTeX/LaTeX workflow.md
- Linux:
  - Linux Manual: Linux/Linux Manual.md
- Windows:
  - Excel Manual: Windows/Excel Manual.md
  - PowerPoint: Windows/PowerPoint.md
  - Powershell Manual: Windows/Powershell Manual.md
  - VSCode: Windows/VSCode.md
  - Windows Manual: Windows/Windows Manual.md
- Audio & Video:
  - FFMpeg: Audio & Video/FFMpeg.md
  - VLC: Audio & Video/VLC.md
- GIS:
  - GIS formats: GIS/GIS formats.md
  - Overpass Manual: GIS/Overpass Manual.md
  - QGIS: GIS/QGIS.md
- Images:
  - Midjourney: Images/Midjourney.md
  - Photopea: Images/Photopea.md
- Arxiv: Arxiv.md
- Google office apps: Google office apps.md
- Hardware Manual: Hardware Manual.md
- index: index.md
- Markdown: Markdown.md
- Network: Network.md
- Security: Security.md
- vscode: vscode.md
- Web Tricks: Web Tricks.md
- XML: XML.md
- YAML: YAML.md
- Zotero: Zotero.md
site_name: Manuals
theme:
  name: mkdocs
  navigation_depth: 8
